/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.yoshikimoji.oss.phonecode.Converter;
import org.junit.Test;
import static org.junit.Assert.*;

public class ConverterTest {
    @Test public void testFindAreaByPhoneMethod() {
        assertEquals("泉州", Converter.findAreaByPhone("0595"));
    }
}
